// ABI generated by Foundry (contracts/out/TaskEscrow.sol/TaskEscrow.json)
// Re-exported here so the API doesn't need to reach into the contracts directory.

export const TASK_ESCROW_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_feeBps", type: "uint16" },
      { name: "_autoApproveDelay", type: "uint256" },
      { name: "_claimTimeout", type: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createTask",
    inputs: [
      { name: "taskId", type: "bytes32" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "claimTask",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitResult",
    inputs: [
      { name: "taskId", type: "bytes32" },
      { name: "resultHash", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approveResult",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "expireTask",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "releaseClaim",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "releaseStaleClaimTask",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getTask",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [
      {
        name: "",
        type: "tuple",
        components: [
          { name: "requester", type: "address" },
          { name: "worker", type: "address" },
          { name: "amount", type: "uint256" },
          { name: "deadline", type: "uint256" },
          { name: "claimedAt", type: "uint256" },
          { name: "status", type: "uint8" },
          { name: "resultHash", type: "bytes32" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeBps",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingFees",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "autoApprove",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "autoApproveAvailableAt",
    inputs: [{ name: "taskId", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "autoApproveDelay",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimTimeout",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawFees",
    inputs: [{ name: "to", type: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  // Events
  {
    type: "event",
    name: "TaskCreated",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "requester", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
      { name: "deadline", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TaskClaimed",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "worker", type: "address", indexed: true },
    ],
  },
  {
    type: "event",
    name: "ResultSubmitted",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "resultHash", type: "bytes32", indexed: false },
    ],
  },
  {
    type: "event",
    name: "ResultApproved",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "workerPayout", type: "uint256", indexed: false },
      { name: "fee", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "TaskReleased",
    inputs: [
      { name: "taskId", type: "bytes32", indexed: true },
      { name: "releasedBy", type: "address", indexed: true },
    ],
  },
  // Errors
  { type: "error", name: "TaskAlreadyExists", inputs: [] },
  { type: "error", name: "TaskNotFound", inputs: [] },
  { type: "error", name: "NotRequester", inputs: [] },
  { type: "error", name: "NotWorker", inputs: [] },
  { type: "error", name: "AutoApproveNotReady", inputs: [] },
  { type: "error", name: "ClaimNotExpired", inputs: [] },
  { type: "error", name: "DeadlinePassed", inputs: [] },
  { type: "error", name: "DeadlineNotPassed", inputs: [] },
  { type: "error", name: "NoValueSent", inputs: [] },
  { type: "error", name: "FeeTooHigh", inputs: [] },
  { type: "error", name: "TransferFailed", inputs: [] },
  {
    type: "error",
    name: "WrongStatus",
    inputs: [
      { name: "expected", type: "uint8" },
      { name: "actual", type: "uint8" },
    ],
  },
] as const;
