import { Hono } from "hono";
import { keccak256, toBytes, parseEther } from "viem";
import { eq, and, sql } from "drizzle-orm";
import { db } from "../db";
import { tasks, agentPubkeys } from "../db/schema";
import { broadcastSignedTx, readTask } from "../chain/escrow";
import { requireAuth } from "../middleware/auth";

// Hono context carries the signer address injected by requireAuth.
type Variables = { signer: `0x${string}` };
const router = new Hono<{ Variables: Variables }>();

// ─── GET /tasks ───────────────────────────────────────────────────────────────
// Public — no auth required. Optional ?status= and ?requester= filters.

router.get("/", async (c) => {
  const statusFilter    = c.req.query("status") as string | undefined;
  const requesterFilter = c.req.query("requester")?.toLowerCase();

  const where = and(
    statusFilter    ? eq(tasks.status, statusFilter as any) : undefined,
    requesterFilter ? eq(sql`lower(${tasks.requester})`, requesterFilter) : undefined,
  );

  const rows = await db.select().from(tasks).where(where);
  return c.json({ tasks: rows.map(serialize) });
});

// ─── GET /tasks/:id ───────────────────────────────────────────────────────────
// Public — no auth required. Syncs fresh status from chain.

router.get("/:id", async (c) => {
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);

  const onchain = await readTask(task.onchainId as `0x${string}`);
  const [updated] = await db
    .update(tasks)
    .set({
      status: onchain.status as any,
      worker: onchain.worker ?? task.worker ?? undefined,
      resultHash: onchain.resultHash ?? task.resultHash ?? undefined,
      updatedAt: new Date(),
    })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json(serialize(updated));
});

// ─── GET /tasks/:id/pubkeys ───────────────────────────────────────────────────
// Public — returns known secp256k1 public keys for requester and worker.
// Workers call this to look up the requester pubkey before grantTaskAccess.

router.get("/:id/pubkeys", async (c) => {
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);

  const addresses = [task.requester, task.worker].filter(Boolean) as string[];
  const rows = await db
    .select()
    .from(agentPubkeys)
    .where(sql`${agentPubkeys.address} = ANY(${sql`ARRAY[${sql.join(addresses.map(a => sql`${a.toLowerCase()}`), sql`, `)}]`})`);

  const pubkeys = Object.fromEntries(rows.map(r => [r.address, r.pubkeyHex]));
  return c.json({ pubkeys });
});

// ─── POST /tasks ──────────────────────────────────────────────────────────────
// Create a task and lock ETH in escrow.
//
// Headers: X-Signature, X-Nonce  (EIP-712 auth — see middleware/auth.ts)
// Body (plaintext):
//   id          string   UUID generated by the SDK
//   title       string
//   description string
//   amountEth   string   e.g. "0.01"
//   deadlineDays number
//   signedTx    string   raw signed EVM transaction calling createTask()
//
// Body (encrypted, mutually exclusive with title/description):
//   encryptedPayload    hex  AES-GCM(contentKey, JSON{title,description})
//   keyWrapForRequester hex  ECIES(requesterPubkey, contentKey)

router.post("/", requireAuth, async (c) => {
  const signer = c.get("signer");
  const body = await c.req.json<{
    id: string;
    title?: string;
    description?: string;
    encryptedPayload?: string;
    keyWrapForRequester?: string;
    amountEth: string;
    deadlineDays: number;
    signedTx: `0x${string}`;
  }>();

  const { id, amountEth, deadlineDays, signedTx } = body;
  if (!id || !amountEth || !deadlineDays || !signedTx) {
    return c.json({ error: "missing required fields" }, 400);
  }

  const isEncrypted = !!(body.encryptedPayload && body.keyWrapForRequester);
  if (!isEncrypted && (!body.title || !body.description)) {
    return c.json({ error: "provide either title+description or encryptedPayload+keyWrapForRequester" }, 400);
  }

  const onchainId = keccak256(toBytes(id)) as `0x${string}`;
  const deadlineAt = new Date(Date.now() + deadlineDays * 86_400_000);

  const txHash = await broadcastSignedTx(signedTx);

  const [task] = await db
    .insert(tasks)
    .values({
      id,
      onchainId,
      requester: signer,
      amountWei: parseEther(amountEth),
      title: isEncrypted ? "" : body.title!,
      description: isEncrypted ? "" : body.description!,
      encryptedPayload: body.encryptedPayload ?? null,
      keyWrapForRequester: body.keyWrapForRequester ?? null,
      status: "open",
      deadlineAt,
    })
    .returning();

  return c.json({ ...serialize(task), txHash }, 201);
});

// ─── POST /tasks/:id/claim ────────────────────────────────────────────────────
// Headers: X-Signature, X-Nonce
// Body:
//   signedTx  string  raw signed EVM transaction calling claimTask()

router.post("/:id/claim", requireAuth, async (c) => {
  const signer = c.get("signer");
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);
  if (task.status !== "open") return c.json({ error: `task is ${task.status}, not open` }, 409);

  const { signedTx } = await c.req.json<{ signedTx: `0x${string}` }>();
  if (!signedTx) return c.json({ error: "missing signedTx" }, 400);

  const txHash = await broadcastSignedTx(signedTx);

  const [updated] = await db
    .update(tasks)
    .set({ status: "claimed", worker: signer, claimedAt: new Date(), updatedAt: new Date() })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json({ ...serialize(updated), txHash });
});

// ─── POST /tasks/:id/submit ───────────────────────────────────────────────────
// Headers: X-Signature, X-Nonce
// Body (plaintext):
//   result    string  the actual work product text
//   signedTx  string  raw signed EVM transaction calling submitResult()
//
// Body (encrypted):
//   encryptedResult           hex  AES-GCM(resultKey, resultText)
//   resultKeyWrapForRequester hex  ECIES(requesterPubkey, resultKey)
//   signedTx                  string  (on-chain hash = keccak256(encryptedResult))

router.post("/:id/submit", requireAuth, async (c) => {
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);
  if (task.status !== "claimed") return c.json({ error: `task is ${task.status}, not claimed` }, 409);

  const body = await c.req.json<{
    result?: string;
    encryptedResult?: string;
    resultKeyWrapForRequester?: string;
    signedTx: `0x${string}`;
  }>();
  if (!body.signedTx) return c.json({ error: "missing signedTx" }, 400);

  const isEncrypted = !!(body.encryptedResult && body.resultKeyWrapForRequester);
  if (!isEncrypted && !body.result) {
    return c.json({ error: "provide either result or encryptedResult+resultKeyWrapForRequester" }, 400);
  }

  const resultHash = isEncrypted
    ? keccak256(toBytes(body.encryptedResult!))
    : keccak256(toBytes(body.result!));

  const txHash = await broadcastSignedTx(body.signedTx);

  const [updated] = await db
    .update(tasks)
    .set({
      status: "submitted",
      resultContent: isEncrypted ? null : body.result,
      encryptedResult: body.encryptedResult ?? null,
      resultKeyWrapForRequester: body.resultKeyWrapForRequester ?? null,
      resultHash,
      updatedAt: new Date(),
    })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json({ ...serialize(updated), txHash });
});

// ─── POST /tasks/:id/grant ────────────────────────────────────────────────────
// Requester-only. Provides the worker's wrapped content key so the worker
// can decrypt the task description.
// Only allowed when status = "claimed" (worker has been assigned).
// Headers: X-Signature, X-Nonce
// Body:
//   keyWrapForWorker  hex  ECIES(workerPubkey, contentKey)

router.post("/:id/grant", requireAuth, async (c) => {
  const signer = c.get("signer");
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);

  if (signer.toLowerCase() !== task.requester.toLowerCase()) {
    return c.json({ error: "only the requester can grant access" }, 403);
  }
  if (task.status !== "claimed") {
    return c.json({ error: `task must be claimed to grant access (is ${task.status})` }, 409);
  }

  const { keyWrapForWorker } = await c.req.json<{ keyWrapForWorker: string }>();
  if (!keyWrapForWorker) return c.json({ error: "missing keyWrapForWorker" }, 400);

  const [updated] = await db
    .update(tasks)
    .set({ keyWrapForWorker, updatedAt: new Date() })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json(serialize(updated));
});

// ─── POST /tasks/:id/approve ──────────────────────────────────────────────────
// Headers: X-Signature, X-Nonce
// Body:
//   signedTx  string  raw signed EVM transaction calling approveResult()

router.post("/:id/approve", requireAuth, async (c) => {
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);
  if (task.status !== "submitted") return c.json({ error: `task is ${task.status}, not submitted` }, 409);

  // Verify the approver is the original requester
  const signer = c.get("signer");
  if (signer.toLowerCase() !== task.requester.toLowerCase()) {
    return c.json({ error: "only the requester can approve" }, 403);
  }

  const { signedTx } = await c.req.json<{ signedTx: `0x${string}` }>();
  if (!signedTx) return c.json({ error: "missing signedTx" }, 400);

  const txHash = await broadcastSignedTx(signedTx);

  const [updated] = await db
    .update(tasks)
    .set({ status: "approved", updatedAt: new Date() })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json({ ...serialize(updated), txHash });
});

// ─── POST /tasks/:id/release ──────────────────────────────────────────────────
// Requester-only. Voluntarily releases a claimed task back to Open.
// Headers: X-Signature, X-Nonce
// Body:
//   signedTx  string  raw signed EVM transaction calling releaseClaim()

router.post("/:id/release", requireAuth, async (c) => {
  const signer = c.get("signer");
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);

  if (signer.toLowerCase() !== task.requester.toLowerCase()) {
    return c.json({ error: "only the requester can release" }, 403);
  }
  if (task.status !== "claimed") {
    return c.json({ error: `task is ${task.status}, not claimed` }, 409);
  }

  const { signedTx } = await c.req.json<{ signedTx: `0x${string}` }>();
  if (!signedTx) return c.json({ error: "missing signedTx" }, 400);

  const txHash = await broadcastSignedTx(signedTx);

  const [updated] = await db
    .update(tasks)
    .set({
      status: "open",
      worker: null,
      claimedAt: null,
      keyWrapForWorker: null,
      updatedAt: new Date(),
    })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json({ ...serialize(updated), txHash });
});

// ─── Serialise DB row ─────────────────────────────────────────────────────────

function serialize(task: typeof tasks.$inferSelect) {
  return {
    id:          task.id,
    onchainId:   task.onchainId,
    requester:   task.requester,
    worker:      task.worker,
    title:       task.title,
    description: task.description,
    amountWei:   task.amountWei?.toString(),
    status:      task.status,
    result:      task.resultContent,
    resultHash:  task.resultHash,
    deadlineAt:  task.deadlineAt.toISOString(),
    claimedAt:   task.claimedAt?.toISOString() ?? null,
    createdAt:   task.createdAt.toISOString(),
    updatedAt:   task.updatedAt.toISOString(),
    // Encrypted fields
    encryptedPayload:          task.encryptedPayload,
    keyWrapForRequester:       task.keyWrapForRequester,
    keyWrapForWorker:          task.keyWrapForWorker,
    encryptedResult:           task.encryptedResult,
    resultKeyWrapForRequester: task.resultKeyWrapForRequester,
  };
}

export default router;
