import { Hono } from "hono";
import { keccak256, toBytes, parseEther } from "viem";
import { eq } from "drizzle-orm";
import { db } from "../db";
import { tasks } from "../db/schema";
import { broadcastSignedTx, readTask } from "../chain/escrow";
import { requireAuth } from "../middleware/auth";

// Hono context carries the signer address injected by requireAuth.
type Variables = { signer: `0x${string}` };
const router = new Hono<{ Variables: Variables }>();

// ─── GET /tasks ───────────────────────────────────────────────────────────────
// Public — no auth required. Optional ?status= filter.

router.get("/", async (c) => {
  const statusFilter = c.req.query("status") as string | undefined;
  const rows = statusFilter
    ? await db.select().from(tasks).where(eq(tasks.status, statusFilter as any))
    : await db.select().from(tasks);
  return c.json({ tasks: rows.map(serialize) });
});

// ─── GET /tasks/:id ───────────────────────────────────────────────────────────
// Public — no auth required. Syncs fresh status from chain.

router.get("/:id", async (c) => {
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);

  const onchain = await readTask(task.onchainId as `0x${string}`);
  const [updated] = await db
    .update(tasks)
    .set({
      status: onchain.status as any,
      worker: onchain.worker ?? task.worker ?? undefined,
      resultHash: onchain.resultHash ?? task.resultHash ?? undefined,
      updatedAt: new Date(),
    })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json(serialize(updated));
});

// ─── POST /tasks ──────────────────────────────────────────────────────────────
// Create a task and lock ETH in escrow.
//
// Headers: X-Signature, X-Nonce  (EIP-712 auth — see middleware/auth.ts)
// Body:
//   id          string   UUID generated by the SDK (also used to derive onchainId)
//   title       string
//   description string
//   amountEth   string   e.g. "0.01"
//   deadlineDays number
//   signedTx    string   raw signed EVM transaction calling createTask()

router.post("/", requireAuth, async (c) => {
  const signer = c.get("signer");
  const body = await c.req.json<{
    id: string;
    title: string;
    description: string;
    amountEth: string;
    deadlineDays: number;
    signedTx: `0x${string}`;
  }>();

  const { id, title, description, amountEth, deadlineDays, signedTx } = body;
  if (!id || !title || !description || !amountEth || !deadlineDays || !signedTx) {
    return c.json({ error: "missing required fields" }, 400);
  }

  const onchainId = keccak256(toBytes(id)) as `0x${string}`;
  const deadlineAt = new Date(Date.now() + deadlineDays * 86_400_000);

  const txHash = await broadcastSignedTx(signedTx);

  const [task] = await db
    .insert(tasks)
    .values({
      id,
      onchainId,
      requester: signer,
      amountWei: parseEther(amountEth),
      title,
      description,
      status: "open",
      deadlineAt,
    })
    .returning();

  return c.json({ ...serialize(task), txHash }, 201);
});

// ─── POST /tasks/:id/claim ────────────────────────────────────────────────────
// Headers: X-Signature, X-Nonce
// Body:
//   signedTx  string  raw signed EVM transaction calling claimTask()

router.post("/:id/claim", requireAuth, async (c) => {
  const signer = c.get("signer");
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);
  if (task.status !== "open") return c.json({ error: `task is ${task.status}, not open` }, 409);

  const { signedTx } = await c.req.json<{ signedTx: `0x${string}` }>();
  if (!signedTx) return c.json({ error: "missing signedTx" }, 400);

  const txHash = await broadcastSignedTx(signedTx);

  const [updated] = await db
    .update(tasks)
    .set({ status: "claimed", worker: signer, updatedAt: new Date() })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json({ ...serialize(updated), txHash });
});

// ─── POST /tasks/:id/submit ───────────────────────────────────────────────────
// Headers: X-Signature, X-Nonce
// Body:
//   result    string  the actual work product text
//   signedTx  string  raw signed EVM transaction calling submitResult()

router.post("/:id/submit", requireAuth, async (c) => {
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);
  if (task.status !== "claimed") return c.json({ error: `task is ${task.status}, not claimed` }, 409);

  const { result, signedTx } = await c.req.json<{ result: string; signedTx: `0x${string}` }>();
  if (!result || !signedTx) return c.json({ error: "missing result or signedTx" }, 400);

  const resultHash = keccak256(toBytes(result));
  const txHash = await broadcastSignedTx(signedTx);

  const [updated] = await db
    .update(tasks)
    .set({ status: "submitted", resultContent: result, resultHash, updatedAt: new Date() })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json({ ...serialize(updated), txHash });
});

// ─── POST /tasks/:id/approve ──────────────────────────────────────────────────
// Headers: X-Signature, X-Nonce
// Body:
//   signedTx  string  raw signed EVM transaction calling approveResult()

router.post("/:id/approve", requireAuth, async (c) => {
  const [task] = await db.select().from(tasks).where(eq(tasks.id, c.req.param("id")));
  if (!task) return c.json({ error: "task not found" }, 404);
  if (task.status !== "submitted") return c.json({ error: `task is ${task.status}, not submitted` }, 409);

  // Verify the approver is the original requester
  const signer = c.get("signer");
  if (signer.toLowerCase() !== task.requester.toLowerCase()) {
    return c.json({ error: "only the requester can approve" }, 403);
  }

  const { signedTx } = await c.req.json<{ signedTx: `0x${string}` }>();
  if (!signedTx) return c.json({ error: "missing signedTx" }, 400);

  const txHash = await broadcastSignedTx(signedTx);

  const [updated] = await db
    .update(tasks)
    .set({ status: "approved", updatedAt: new Date() })
    .where(eq(tasks.id, task.id))
    .returning();

  return c.json({ ...serialize(updated), txHash });
});

// ─── Serialise DB row ─────────────────────────────────────────────────────────

function serialize(task: typeof tasks.$inferSelect) {
  return {
    id:          task.id,
    onchainId:   task.onchainId,
    requester:   task.requester,
    worker:      task.worker,
    title:       task.title,
    description: task.description,
    amountWei:   task.amountWei?.toString(),
    status:      task.status,
    result:      task.resultContent,
    resultHash:  task.resultHash,
    deadlineAt:  task.deadlineAt.toISOString(),
    createdAt:   task.createdAt.toISOString(),
    updatedAt:   task.updatedAt.toISOString(),
  };
}

export default router;
